name: ADSE_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - numpy=1.20.1
  - matplotlib=3.3.4
  - scipy=1.6.1
  - pandas=1.2.3
  - shapely=1.7.1
  - opencv=4.5.1
  - filterpy=1.4.5
  - sympy=1.7.1
  - pytorch=1.6.0
  - flake8=3.8.4
  - tqdm=4.59.0
  - ipywidgets=7.6.3
  - seaborn=0.11.1
  - scikit-learn=0.24.1
  - tqdm=4.59.0
  - joblib=1.0.1
  - osmnx==1.0.1
  - networkx==2.5
  - plotly==4.14.3
  - pytest==6.2.2
  - backports==1.0
  - libprotobuf=3.13.0.1
  - paho-mqtt=1.5.1
  - prompt-toolkit=3.0.17
  - zeromq=4.3.4
  - webencodings=0.5.1
  - wheel=0.36.2
  - pyproj=3.0.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - torchvision=0.7.0=py38_cu102
  - imgaug=0.4.0=py_1
