#==============#
# Camera Model #
#==============#

Camera.name: "IAC monocular"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 4640
Camera.fy: 4640
Camera.cx: 1032
Camera.cy: 772

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.fps: 30.0
Camera.cols: 2064
Camera.rows: 1544

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 10000
Feature.scale_factor: 1.1
Feature.num_levels: 8
Feature.ini_fast_threshold: 80
Feature.min_fast_threshold: 60
Feature.mask_rectangles:
  - [0.0, 1.0, 0.6, 1.0]

#=================#
# Init Parameters #
#=================#

Initializer.parallax_deg_threshold: 0.5
Initializer.num_min_triangulated_pts: 40
Initializer.scaling_factor: 2
Initializer.num_ba_iterations: 100
Initializer.reprojection_error_threshold: 10
Initializer.num_ransac_iterations: 150

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer.keyframe_size: 0.06
PangolinViewer.keyframe_line_width: 1
PangolinViewer.graph_line_width: 1
PangolinViewer.point_size: 2
PangolinViewer.camera_size: 0.07
PangolinViewer.camera_line_width: 2
PangolinViewer.viewpoint_x: 0
PangolinViewer.viewpoint_y: -20
PangolinViewer.viewpoint_z: -0.1
PangolinViewer.viewpoint_f: 2800
