(cl:in-package nuscenes2bag-msg)
(cl:export '(POSE-VAL
          POSE
          DYN_PROP-VAL
          DYN_PROP
          ID-VAL
          ID
          RCS-VAL
          RCS
          VX-VAL
          VX
          VY-VAL
          VY
          VX_COMP-VAL
          VX_COMP
          VY_COMP-VAL
          VY_COMP
          IS_QUALITY_VALID-VAL
          IS_QUALITY_VALID
          AMBIG_STATE-VAL
          AMBIG_STATE
          X_RMS-VAL
          X_RMS
          Y_RMS-VAL
          Y_RMS
          INVALID_STATE-VAL
          INVALID_STATE
          PDH0-VAL
          PDH0
          VX_RMS-VAL
          VX_RMS
          VY_RMS-VAL
          VY_RMS
))