scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    # robot_frame_id: "rear_axis_middle"
    robot_frame_id: "center_of_gravity"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 2
    trans_for_mapupdate: 3.0 #1.5
    vg_size_for_input: 0.5
    vg_size_for_map: 0.1
    scan_min_range: 1.0
    scan_max_range: 200.0
    scan_period: 0.1
    map_publish_period: 2.0
    num_targeted_cloud: 20
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: true
    debug_flag: false

graph_based_slam:
    ros__parameters:
      ndt_resolution: 1.0
      ndt_num_threads: 2
      voxel_leaf_size: 3.0 #0.1
      loop_detection_period: 10000
      threshold_loop_closure_score: 0.7
      distance_loop_closure: 500.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      use_save_map_in_loop: true

